### ISSUE TITLE
Actualitzar script de creació de base de dades: postgresql

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/emiserv#11]

**Comment by gdeignacio-fundaciobit** [comment]
Al fitxer emiserv_02_constraint.sql manca definir la clau primària per a la taula AUTORIZACION_CA.

Ex.   ALTER TABLE AUTORIZACION_CA ADD CONSTRAINT AUTORIZACION_CA_PK PRIMARY KEY(CODCA);

**Comment by gdeignacio-fundaciobit** [comment]
A la versió 2.0, al fitxer emiserv_01_create_table.sql obtenim l'error

ERROR:  syntax error at or near "GENERATED"
LINE 19: CREATE TABLE ems_acl_sid (id BIGINT GENERATED BY DEFAULT AS ...
                                             ^
SQL state: 42601
Character: 3659
