### ISSUE TITLE
No mostra el XML de la petició si l'estat és erroni

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/emiserv#26]
No apareix la petició XML a la comunicació SCSP si ha hagut qualque error. Si l'estat és 'Tramitada' sí es mostra

**Comment by josepg-limit** [comment]
Aquest problema es dona només en les peticions asíncrones i pareix un bug de les llibreries SCSP.
En les peticions síncrones, per a cada petició, s'emmagatzemen diferents files a la taula CORE_TOKEN_DATA. Cada fila correspon a un tipus de missatge intercanviat entre emisor i requirent (tipus 0: petició, tipus 3: resposta, tipus 4: error, ...).
Però en les peticions múltiples només s'emmagatzema el missatge d'error (tipus 4) i la fila de la petició (tipus 0) no apareix.

És per això que EMISERV no pot mostrar el missatge XML de la petició.
