### ISSUE TITLE
Afegir manteniment de taula de gestió CORE_ORGANISMO_CESIONARIO

### ISSUE THREAD

**Issue by gdeignacio-fundaciobit** [GovernIB/emiserv#37]
Per a donar d'alta una clau privada s'ha de satisfer la restricció següent

ALTER TABLE CORE_CLAVE_PRIVADA add CONSTRAINT CLAVE_PRIVADA_ORG FOREIGN KEY (ORGANISMO) REFERENCES CORE_ORGANISMO_CESIONARIO (ID);

Pero no es possible afegir una fila a la taula CORE_ORGANISMO_CESIONARIO fent servir l'aplicacio. Cal un formulari per no haver de insertar mitjançant un script.

**Comment by atrobat-dgtic** [comment]
Aquesta ISSUE era per fer el manteniment de la taula CORE_EM_ORGANISMO_CESIONARIO, s'ha fet el maneteniment d'una altra taula que no és aquesta.  Reobriré l'issue per què és important que el més prest possible estigui aquest manteniment fet.

**Comment by josepg-limit** [comment]
Aquest error es va arreglar a la versió 2.0.3.
Sembla que s'ha reobert comprovant a la 2.0.2.

Queda pendent de validar que en les version 2.0.3+ funcioni correctament
