### ISSUE TITLE
Properties EMISERV 2.0 no contingudes a l'arxiu emiserv.properties

### ISSUE THREAD

**Issue by gdeignacio-fundaciobit** [GovernIB/emiserv#39]
1. A l'arxiu emiserv-persistence/src/main/resources/application.properties
    La propietat spring.jpa.properties.hibernate.dialect està predeterminada i coincideix amb el valor de es.caib.emiserv.hibernate.dialect
    
    spring.jpa.properties.hibernate.dialect=es.caib.emiserv.persist.dialect.OracleCaibDialect
    Obliga a modificarla i recompilar si la base de dades es diferent de Oracle

2. A l'arxiu emisrv-api-externa/src/main/webapp/WEB-INF/classes/scsp-service.properties
    La propietat hibernate.dialect està predeterminada  i coincideix amb el valor de es.caib.emiserv.hibernate.dialect 
    La propietat jndiName conté el mateix valor que  es.caib.emiserv.datasource.jndi 
    Obliga a modificarla i recompilar si la base de dades es diferent de Oracle

**Comment by josepg-limit** [comment]
En teoria per a solucionar el punt 1 no és necessari recompilar l'aplicació donat que les propietats definides als fitxers de properties tenen prioritat a damunt les definides al codi font. Seria possible definir la següent propietat i que l'aplicació funcioni correctament sobre PostgreSQL sense necessitat de recompilar l'aplicació.

    spring.jpa.properties.hibernate.dialect=es.caib.emiserv.persist.dialect.PostgreSQLCaibDialect

Per a confirmar-ho al 100% hauriem de fer alguna prova.

En el segon punt la cosa se complica perquè el mòdul emiserv-api-externa és un overlay de l'emissor SCSP i aquí noltros no controlam com es configura el dialecte de Hibernate. Es podria fer alguna millora al respecte com, per exemple, afegir un profile de Maven per a poder compilar el projecte amb PostgreSQL, però canviar de base de dades sempre ens obligaria a recompilar l'aplicació.

**Comment by josepg-limit** [comment]
Hem trobat una forma de sobreescriure els fitxers del war de l'emissor SCSP. Amb això segurament aconseguirem configurar el dialecte d'hibernate a partir del contingut del fitxer de properties i no farà falta recompilar l'aplicació per a utilitzar una base de dades PostgreSQL.
