### ISSUE TITLE
La configuració d'idioma no funciona correctament

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/emiserv#45]
No coincideixen els textos de les seccions i els paginats.

![image](https://user-images.githubusercontent.com/58417501/133422458-a968b5bc-b71b-404d-93bf-61b5387ecd52.png)

A més, si intentes canviar el idioma des de la configuració d'usuari es recarrega la modal en lloc de la pàgina principal

![image](https://user-images.githubusercontent.com/58417501/133422160-aafc8771-588b-405d-af1a-6514c51ee4e7.png)
![image](https://user-images.githubusercontent.com/58417501/133422109-d1fa269c-6d5e-4a67-894c-50dd2a738c9b.png)

**Comment by acuevas-dgtic** [comment]
Continua igual

**Comment by josepg-limit** [comment]
La pre-release que se ha desplegado en proves no contenia la solución al problema. Lo incluiremos en la siguiente pre-release.

**Comment by acuevas-dgtic** [comment]
La finestra de configuració ja funciona bé pero continuen apareixent textos en castellà quan tens l'idioma en català.

![image](https://user-images.githubusercontent.com/58417501/134148358-680330a1-969b-44a7-8996-6dd7c5a74cf8.png)

**Comment by acuevas-dgtic** [comment]
Esta isue sigue sin resolverse. La movemos a la 2.0.2

**Comment by acuevas-dgtic** [comment]
En producción con la 2.0.1 sigue saliendo en castellano
