### ISSUE TITLE
Afegir columna procediment al llistat d'auditories a backoffices i a l'enrutador

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/emiserv#57]
Abans del camp servei

![image](https://user-images.githubusercontent.com/58417501/151142637-c185ee56-25ee-4caa-8ba4-82345a7136d3.png)

**Comment by josepg-limit** [comment]
S'ha afegit la columna de procediment als dos llistats de auditoria, però com que hi pot haver múltiples procediments en una mateixa petició, no s'implementa la ordenació per aquesta columna.
