### ISSUE TITLE
Instalar la llibreria seyconsession-common al repositori local del projecte.

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/emiserv#9]

**Comment by gdeignacio-fundaciobit** [comment]
Vista la modificació, al fer mvn package obtenim el resultat:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Emissor SCSP CAIB 1.4 .............................. SUCCESS [  2.016 s]
[INFO] emiserv-core-api ................................... SUCCESS [  4.417 s]
[INFO] emiserv-backoffice ................................. SUCCESS [  1.584 s]
[INFO] emiserv-lib-common ................................. SUCCESS [  0.011 s]
[INFO] Emissor SCSP CAIB webapp ........................... FAILURE [  3.620 s]
[INFO] emiserv-plugin ..................................... SKIPPED
[INFO] emiserv-core ....................................... SKIPPED
[INFO] emiserv-plugin-impl ................................ SKIPPED
[INFO] emiserv-ear 1.4 .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.238 s
[INFO] Finished at: 2019-03-14T11:43:29+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project emiserv-war: Could not resolve dependencies for project es.caib.emiserv:emiserv-war:war:1.4: Could not find artifact es.scsp:scsp-emisor:war:4-6-0 at specified path E:\Proyectos\maven\emiserv\emiserv-war\scsp-emisor-4-6-0.war -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :emiserv-war

**Comment by josepg-limit** [comment]
Per a compilar el projecte necessitau posar el WAR de l'emissor SCSP versió 4.6.0 a dins la carpeta emiserv-war. Podeu obtenir aquest fitxer de la secció de descàrregues de la pàgina del projecte SCSP (https://administracionelectronica.gob.es/ctt/scsp)
